--alter table REGISTRO add [proceso_registro] bit null
--Alter table REGISTRO alter column horas_laboradas decimal(10,2)
--Alter table REGISTRO alter column horas_extras decimal(10,2)
--Alter table COLABORADOR alter column precio_hora decimal(10,2)